### ISSUE TITLE
zero coefficients of linear functions are not discarded

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34887]
<div id="comment:0"></div>

When creating linear functions, 0 coefficients are currently kept:

```
sage: M = MixedIntegerLinearProgram(check_redundant=True)
sage: x = M.new_variable()
sage: c1 = x[0] <= x[0] + x[1]
sage: c2 = 0 <= x[1]
sage: c3 = 0 <= x[1] + 0*x[2]
sage: M.add_constraint(c1, return_indices=True)
[0]
sage: M.add_constraint(c2, return_indices=True)
[1]
sage: M.add_constraint(c3, return_indices=True)
[2]
sage: M.show()
Maximization:
  

Constraints:
  c1: - x2 <= 0.0
  c2: - x2 <= 0.0
  c3: - x2 <= 0.0
Variables:
  x1 = x_0 is a continuous variable (min=-oo, max=+oo)
  x2 = x_1 is a continuous variable (min=-oo, max=+oo)
  x3 = x_2 is a continuous variable (min=-oo, max=+oo)
```
The proposed fix is to eliminate zero coefficients only in `_is_redundant_constraint`.

I am not sure whether this is a good idea, however, `LinearFunction.is_zero` and `equals` check all the coefficients, so this was a conscious choice by the original developers.

CC:  @mkoeppe

Component: **linear programming**

Author: **Martin Rubey**

Branch/Commit: **[u/mantepse/discard_zero_coefficients](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/discard_zero_coefficients) @ [`81e33a8`](https://github.com/sagemath/sagetrac-mirror/commit/81e33a84116d011bbfa12df0cd08d1938d196d7e)**

_Issue created by migration from https://trac.sagemath.org/ticket/34887_
